/*
 * JS for contacts generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '370f9943-f52a-44a8-aaa9-5433e842b0a0';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Location",
    "location": "Location.html"
}, {
    "name": "Kontakte",
    "location": "Kontakte.html"
}, {
    "name": "ort",
    "location": "ort.html"
}, {
    "name": "contacts",
    "location": "contacts.html"
}, {
    "name": "DialogInvite",
    "location": "DialogInvite.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

contacts_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_18': 'contacts_mobilelabel_18',
        'query_input': 'contacts_query_input',
        'search_button': 'contacts_search_button',
        'contacts_list': 'contacts_contacts_list',
        'mobilelistitem_5': 'contacts_mobilelistitem_5',
        'mobilelistitembutton_6': 'contacts_mobilelistitembutton_6',
        'contact_name': 'contacts_contact_name',
        'phone_number': 'contacts_phone_number'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'contacts';

    /*
     * Nonvisual components
     */
    var datasources = [];

    contacts1 = new Apperyio.DataSource(ContactsService, {
        'onBeforeSend': function(jqXHR) {

        },
        'onComplete': function(jqXHR, textStatus) {

            Apperyio.refreshScreenFormElements("contacts");
        },
        'onSuccess': function(data) {},
        'onError': function(jqXHR, textStatus, errorThrown) {},
        'responseMapping': [{
            'PATH': ['$'],
            'ID': 'mobilelistitem_5',
            'SET': [{
                'PATH': ['name', 'formatted'],
                'ID': 'contact_name',
                'ATTR': '@'
            }, {
                'PATH': ['phoneNumbers[0]', 'value'],
                'ID': 'phone_number',
                'ATTR': '@'
            }]
        }],
        'requestMapping': [{
            'PATH': ['options', 'filter'],
            'TYPE': 'STRING',
            'ID': 'query_input',
            'ATTR': 'value'
        }, {
            'PATH': ['options', 'multiple'],
            'TYPE': 'STRING',
            'ATTR': 'true'
        }, {
            'PATH': ['params', 'fields'],
            'TYPE': 'STRING',
            'ATTR': '*'
        }]
    });

    datasources.push(contacts1);

    /*
     * Events and handlers
     */

    // Before Show
    var contacts_beforeshow = function() {
            Apperyio.CurrentScreen = "contacts";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var contacts_onLoad = function() {
            contacts_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            contacts_deviceEvents();
            contacts_windowEvents();
            contacts_elementsEvents();
        };

    // screen window events
    var contacts_windowEvents = function() {

            $('#contacts').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var contacts_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var contacts_elementsExtraJS = function() {
            // screen (contacts) extra code

            /* contacts_list */

            listView = $("#contacts_contacts_list");
            theme = listView.attr("data-theme");
            if (typeof theme !== 'undefined') {
                var themeClass = "ui-btn-up-" + theme;
                listItem = $("#contacts_contacts_list .ui-li-static");
                $.each(listItem, function(index, value) {
                    $(this).addClass(themeClass);
                });
            }

            /* mobilelistitem_5 */

        };

    // screen elements handler
    var contacts_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#contacts_mobilecontainer [name="search_button"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        try {
                            contacts1.execute({})
                        } catch (ex) {
                            console.log(ex.name + '  ' + ex.message);
                            hideSpinner();
                        };

                    }
                },
            }, '#contacts_mobilecontainer [name="search_button"]');

            $(document).off("click", '#contacts_mobilecontainer [name="mobilelistitem_5"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        setVar_('myInvite', 'contacts_contact_name', 'text', '', this);
                        Apperyio.navigateTo('DialogInvite', {
                            transition: 'pop'
                        });

                    }
                },
            }, '#contacts_mobilecontainer [name="mobilelistitem_5"]');

        };

    $(document).off("pagebeforeshow", "#contacts").on("pagebeforeshow", "#contacts", function(event, ui) {
        contacts_beforeshow();
    });

    if (runBeforeShow) {
        contacts_beforeshow();
    } else {
        contacts_onLoad();
    }
};

$(document).off("pagecreate", "#contacts").on("pagecreate", "#contacts", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    contacts_js();
});