/*
 * JS for DialogInvite generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '370f9943-f52a-44a8-aaa9-5433e842b0a0';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Location",
    "location": "Location.html"
}, {
    "name": "Kontakte",
    "location": "Kontakte.html"
}, {
    "name": "ort",
    "location": "ort.html"
}, {
    "name": "contacts",
    "location": "contacts.html"
}, {
    "name": "DialogInvite",
    "location": "DialogInvite.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

DialogInvite_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelabel_2': 'DialogInvite_mobilelabel_2',
        'mobilelist_12': 'DialogInvite_mobilelist_12',
        'mobilelistitem_13': 'DialogInvite_mobilelistitem_13',
        'mobilelistitembutton_14': 'DialogInvite_mobilelistitembutton_14',
        'invitedLabel': 'DialogInvite_invitedLabel',
        'mobilegrid_5': 'DialogInvite_mobilegrid_5',
        'mobilegridcell_6': 'DialogInvite_mobilegridcell_6',
        'mobilegridcell_7': 'DialogInvite_mobilegridcell_7',
        'mobilebutton_3': 'DialogInvite_mobilebutton_3',
        'mobilegridcell_10': 'DialogInvite_mobilegridcell_10',
        'mobilebutton_4': 'DialogInvite_mobilebutton_4',
        'mobilegridcell_11': 'DialogInvite_mobilegridcell_11',
        'mobilegrid_53': 'DialogInvite_mobilegrid_53',
        'mobilegridcell_54': 'DialogInvite_mobilegridcell_54',
        'mobilelabel_30': 'DialogInvite_mobilelabel_30',
        'mobilegridcell_55': 'DialogInvite_mobilegridcell_55',
        'am': 'DialogInvite_am',
        'mobilegridcell_56': 'DialogInvite_mobilegridcell_56',
        'mobilelabel_31': 'DialogInvite_mobilelabel_31',
        'mobilegridcell_57': 'DialogInvite_mobilegridcell_57',
        'mobilegrid_34': 'DialogInvite_mobilegrid_34',
        'mobilegridcell_35': 'DialogInvite_mobilegridcell_35',
        'vonH': 'DialogInvite_vonH',
        'mobilegridcell_36': 'DialogInvite_mobilegridcell_36',
        'mobilelabel_41': 'DialogInvite_mobilelabel_41',
        'mobilegridcell_39': 'DialogInvite_mobilegridcell_39',
        'vonM': 'DialogInvite_vonM',
        'mobilegridcell_58': 'DialogInvite_mobilegridcell_58',
        'mobilelabel_32': 'DialogInvite_mobilelabel_32',
        'mobilegridcell_59': 'DialogInvite_mobilegridcell_59',
        'bisUhrzeitGrid': 'DialogInvite_bisUhrzeitGrid',
        'mobilegridcell_44': 'DialogInvite_mobilegridcell_44',
        'bisH': 'DialogInvite_bisH',
        'mobilegridcell_45': 'DialogInvite_mobilegridcell_45',
        'mobilelabel_50': 'DialogInvite_mobilelabel_50',
        'mobilegridcell_48': 'DialogInvite_mobilegridcell_48',
        'bisM': 'DialogInvite_bisM',
        'mobilegridcell_60': 'DialogInvite_mobilegridcell_60',
        'mobilelabel_33': 'DialogInvite_mobilelabel_33',
        'mobilegridcell_61': 'DialogInvite_mobilegridcell_61',
        'ort': 'DialogInvite_ort'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'DialogInvite';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var DialogInvite_beforeshow = function() {
            Apperyio.CurrentScreen = "DialogInvite";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var DialogInvite_onLoad = function() {
            DialogInvite_elementsExtraJS();

            $('[id=DialogInvite_mobilelistitem_13] h3').text('');
            setText('DialogInvite_am', localStorage.getItem('myDate'));
            setText('DialogInvite_vonH', localStorage.getItem('myHour'));
            setText('DialogInvite_bisH', localStorage.getItem('myHour2'));
            setText('DialogInvite_bisM', localStorage.getItem('myMinute'));
            setText('DialogInvite_vonM', localStorage.getItem('myMinute'));
            setText('DialogInvite_invitedLabel', localStorage.getItem('myInvite'));

            // TODO fire device events only if necessary (with JS logic)
            DialogInvite_deviceEvents();
            DialogInvite_windowEvents();
            DialogInvite_elementsEvents();
        };

    // screen window events
    var DialogInvite_windowEvents = function() {

            $('#DialogInvite').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var DialogInvite_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var DialogInvite_elementsExtraJS = function() {
            // screen (DialogInvite) extra code

            /* mobilelist_12 */

            listView = $("#DialogInvite_mobilelist_12");
            theme = listView.attr("data-theme");
            if (typeof theme !== 'undefined') {
                var themeClass = "ui-btn-up-" + theme;
                listItem = $("#DialogInvite_mobilelist_12 .ui-li-static");
                $.each(listItem, function(index, value) {
                    $(this).addClass(themeClass);
                });
            }

            /* mobilelistitem_13 */

        };

    // screen elements handler
    var DialogInvite_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#DialogInvite_mobilecontainer [name="mobilebutton_3"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        localStorage.setItem('invited', '1');

                    }
                },
            }, '#DialogInvite_mobilecontainer [name="mobilebutton_3"]');

            $(document).off("click", '#DialogInvite_mobilecontainer [name="mobilebutton_4"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        closePopup();

                    }
                },
            }, '#DialogInvite_mobilecontainer [name="mobilebutton_4"]');

        };

    $(document).off("pagebeforeshow", "#DialogInvite").on("pagebeforeshow", "#DialogInvite", function(event, ui) {
        DialogInvite_beforeshow();
    });

    if (runBeforeShow) {
        DialogInvite_beforeshow();
    } else {
        DialogInvite_onLoad();
    }
};

$(document).off("pagecreate", "#DialogInvite").on("pagecreate", "#DialogInvite", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    DialogInvite_js();
});