/*
 * JS for Kontakte generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '370f9943-f52a-44a8-aaa9-5433e842b0a0';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Location",
    "location": "Location.html"
}, {
    "name": "Kontakte",
    "location": "Kontakte.html"
}, {
    "name": "ort",
    "location": "ort.html"
}, {
    "name": "contacts",
    "location": "contacts.html"
}, {
    "name": "DialogInvite",
    "location": "DialogInvite.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

Kontakte_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilelist_2': 'Kontakte_mobilelist_2',
        'mobilelistitem_3': 'Kontakte_mobilelistitem_3',
        'mobilelistitembutton_4': 'Kontakte_mobilelistitembutton_4',
        'mobilelistitem_5': 'Kontakte_mobilelistitem_5',
        'mobilelistitembutton_6': 'Kontakte_mobilelistitembutton_6',
        'mobilelistitem_7': 'Kontakte_mobilelistitem_7',
        'mobilelistitembutton_8': 'Kontakte_mobilelistitembutton_8',
        'mobilelistitem_9': 'Kontakte_mobilelistitem_9',
        'mobilelistitembutton_10': 'Kontakte_mobilelistitembutton_10',
        'mobilelistitem_11': 'Kontakte_mobilelistitem_11',
        'mobilelistitembutton_12': 'Kontakte_mobilelistitembutton_12',
        'mobilelistitem_13': 'Kontakte_mobilelistitem_13',
        'mobilelistitembutton_14': 'Kontakte_mobilelistitembutton_14',
        'mobilelistitem_15': 'Kontakte_mobilelistitem_15',
        'mobilelistitembutton_16': 'Kontakte_mobilelistitembutton_16',
        'mobilelistitem_17': 'Kontakte_mobilelistitem_17',
        'mobilelistitembutton_18': 'Kontakte_mobilelistitembutton_18',
        'mobilelistitem_19': 'Kontakte_mobilelistitem_19',
        'mobilelistitembutton_20': 'Kontakte_mobilelistitembutton_20'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'Kontakte';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    var Kontakte_beforeshow = function() {
            Apperyio.CurrentScreen = "Kontakte";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var Kontakte_onLoad = function() {
            Kontakte_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            Kontakte_deviceEvents();
            Kontakte_windowEvents();
            Kontakte_elementsEvents();
        };

    // screen window events
    var Kontakte_windowEvents = function() {

            $('#Kontakte').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var Kontakte_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var Kontakte_elementsExtraJS = function() {
            // screen (Kontakte) extra code

            /* mobilelist_2 */

            listView = $("#Kontakte_mobilelist_2");
            theme = listView.attr("data-theme");
            if (typeof theme !== 'undefined') {
                var themeClass = "ui-btn-up-" + theme;
                listItem = $("#Kontakte_mobilelist_2 .ui-li-static");
                $.each(listItem, function(index, value) {
                    $(this).addClass(themeClass);
                });
            }

            /* mobilelistitem_3 */

            /* mobilelistitem_5 */

            /* mobilelistitem_7 */

            /* mobilelistitem_9 */

            /* mobilelistitem_11 */

            /* mobilelistitem_13 */

            /* mobilelistitem_15 */

            /* mobilelistitem_17 */

            /* mobilelistitem_19 */

        };

    // screen elements handler
    var Kontakte_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

        };

    $(document).off("pagebeforeshow", "#Kontakte").on("pagebeforeshow", "#Kontakte", function(event, ui) {
        Kontakte_beforeshow();
    });

    if (runBeforeShow) {
        Kontakte_beforeshow();
    } else {
        Kontakte_onLoad();
    }
};

$(document).off("pagecreate", "#Kontakte").on("pagecreate", "#Kontakte", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Kontakte_js();
});