/*
 * JS for Location generated by Appery.io
 */

Apperyio.getProjectGUID = function() {
    return '370f9943-f52a-44a8-aaa9-5433e842b0a0';
};

function navigateTo(outcome, useAjax) {
    Apperyio.navigateTo(outcome, useAjax);
}

// Deprecated


function adjustContentHeight() {
    Apperyio.adjustContentHeightWithPadding();
}

function adjustContentHeightWithPadding(_page) {
    Apperyio.adjustContentHeightWithPadding(_page);
}

function setDetailContent(pageUrl) {
    Apperyio.setDetailContent(pageUrl);
}

Apperyio.AppPages = [{
    "name": "Location",
    "location": "Location.html"
}, {
    "name": "Kontakte",
    "location": "Kontakte.html"
}, {
    "name": "ort",
    "location": "ort.html"
}, {
    "name": "contacts",
    "location": "contacts.html"
}, {
    "name": "DialogInvite",
    "location": "DialogInvite.html"
}, {
    "name": "startScreen",
    "location": "startScreen.html"
}];

Location_js = function(runBeforeShow) {

    /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobilebutton_4': 'Location_mobilebutton_4',
        'input': 'Location_input',
        'mobilebutton_7': 'Location_mobilebutton_7',
        'map': 'Location_map',
        'marker_3': 'Location_marker_3',
        'mobilebutton_8': 'Location_mobilebutton_8',
        'mobilegrid_11': 'Location_mobilegrid_11',
        'mobilegridcell_12': 'Location_mobilegridcell_12',
        'mobilelabel_10': 'Location_mobilelabel_10',
        'mobilegridcell_13': 'Location_mobilegridcell_13',
        'latl': 'Location_latl',
        'mobilegridcell_14': 'Location_mobilegridcell_14',
        'mobilelabel_9': 'Location_mobilelabel_9',
        'mobilegridcell_15': 'Location_mobilegridcell_15',
        'longl': 'Location_longl'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fix for jQuery Mobile's footer in Cordova webview on WP8 devices
        var msViewportStyle = document.createElement("style");
        msViewportStyle.appendChild(
        document.createTextNode("@media screen and (orientation: portrait){@-ms-viewport {width: 320px; height: 534px;user-zoom: fixed;zoom: 1;}}" + "@media screen and (orientation:landscape){@-ms-viewport{width:480px;user-zoom:fixed;zoom:1;}}"));
        document.getElementsByTagName("head")[0].appendChild(msViewportStyle);
    }

    Apperyio.CurrentScreen = 'Location';

    /*
     * Nonvisual components
     */
    var datasources = [];

    geolocation1 = new Apperyio.DataSource(GeolocationService, {
        'onBeforeSend': function(jqXHR) {

        },
        'onComplete': function(jqXHR, textStatus) {
            var map = Appery('map');
            map.options['address'] = '';
            map.refresh();

            Apperyio.refreshScreenFormElements("Location");
        },
        'onSuccess': function(data) {
            var map = Appery('map');
            map.options['address'] = '';
            map.refresh();
        },
        'onError': function(jqXHR, textStatus, errorThrown) {
            setText('Location_latl', 'Moep. Da ist was schief gelaufen.');
        },
        'responseMapping': [{
            'PATH': ['coords', 'latitude'],
            'ID': 'map',
            'ATTR': 'latitude'
        }, {
            'PATH': ['coords', 'longitude'],
            'ID': 'map',
            'ATTR': 'longitude'
        }, {
            'PATH': ['coords', 'latitude'],
            'ID': 'latl',
            'ATTR': '@'
        }, {
            'PATH': ['coords', 'longitude'],
            'ID': 'longl',
            'ATTR': '@'
        }],
        'requestMapping': [{
            'PATH': ['options', 'maximumAge'],
            'TYPE': 'STRING',
            'ATTR': '3000'
        }, {
            'PATH': ['options', 'timeout'],
            'TYPE': 'STRING',
            'ATTR': '5000'
        }, {
            'PATH': ['options', 'enableHighAccuracy'],
            'TYPE': 'STRING',
            'ATTR': 'true'
        }, {
            'PATH': ['options', 'watchPosition'],
            'TYPE': 'STRING',
            'ATTR': 'false'
        }]
    });

    datasources.push(geolocation1);

    /*
     * Events and handlers
     */

    // Before Show
    var Location_beforeshow = function() {
            Apperyio.CurrentScreen = "Location";
            for (var idx = 0; idx < datasources.length; idx++) {
                datasources[idx].__setupDisplay();
            }
        };

    // On Load
    var Location_onLoad = function() {
            Location_elementsExtraJS();

            // TODO fire device events only if necessary (with JS logic)
            Location_deviceEvents();
            Location_windowEvents();
            Location_elementsEvents();
        };

    // screen window events
    var Location_windowEvents = function() {

            $('#Location').bind('pageshow orientationchange', function() {
                var _page = this;
                adjustContentHeightWithPadding(_page);
            });

        };

    // device events
    var Location_deviceEvents = function() {
            document.addEventListener("deviceready", function() {

            });
        };

    // screen elements extra js
    var Location_elementsExtraJS = function() {
            // screen (Location) extra code

            /* map */

            $("[name = 'map']").wrap("<div/>");
            $("[name = 'map']").parent().css("margin-left", $("[name = 'map']").css("margin-left"));
            $("[name = 'map']").parent().css("margin-right", $("[name = 'map']").css("margin-right"));
            $("[name = 'map']").css("margin-left", '0');
            $("[name = 'map']").css("margin-right", '0');

            var map_options = {
                markerSourceName: "map_markers",
                latitude: "",
                longitude: "",
                address: "Uni Lübeck",
                zoom: 14,
                showLocationMarker: true
            }

            Apperyio.__registerComponent('map', new Apperyio.ApperyMapComponent("map", map_options));
            $("[name='map_markers'] [apperytype='marker']").attr("reRender", "map");
            $("[name='map']").closest("[data-role='page']").bind({
                pagecontainershow: function() {
                    if (Apperyio('map') != undefined) {
                        Apperyio('map').refresh();
                    }
                }
            });

        };

    // screen elements handler
    var Location_elementsEvents = function() {
            $(document).on("click", "a :input,a a,a fieldset label", function(event) {
                event.stopPropagation();
            });

            $(document).off("click", '#Location_mobileheader [name="mobilebutton_4"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        Apperyio.navigateTo('startScreen', {
                            transition: 'fade',
                            reverse: false
                        });

                    }
                },
            }, '#Location_mobileheader [name="mobilebutton_4"]');

            $(document).off("click", '#Location_mobilecontainer [name="mobilebutton_7"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        var location = Appery('input').val();
                        if (location == '') {
                            alert('Die Örtlichkeit nicht vergessen!');
                            return;
                        }
                        var map = Appery('map');
                        map.options['address'] = location;
                        map.refresh();

                    }
                },
            }, '#Location_mobilecontainer [name="mobilebutton_7"]');

            $(document).off("click", '#Location_mobilecontainer [name="mobilebutton_8"]').on({
                click: function() {
                    if (!$(this).attr('disabled')) {
                        try {
                            geolocation1.execute({})
                        } catch (ex) {
                            console.log(ex.name + '  ' + ex.message);
                            hideSpinner();
                        };

                    }
                },
            }, '#Location_mobilecontainer [name="mobilebutton_8"]');

        };

    $(document).off("pagebeforeshow", "#Location").on("pagebeforeshow", "#Location", function(event, ui) {
        Location_beforeshow();
    });

    if (runBeforeShow) {
        Location_beforeshow();
    } else {
        Location_onLoad();
    }
};

$(document).off("pagecreate", "#Location").on("pagecreate", "#Location", function(event, ui) {
    Apperyio.processSelectMenu($(this));
    Location_js();
});